# Generated by Django 6.0.4 on 2026-05-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgparecord',
            old_name='total_credit_point',
            new_name='total_credit_points',
        ),
    ]
