# Generated by Django 6.0.4 on 2026-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_total_credit_point_cgparecord_total_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgparecord',
            name='cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cgparecord',
            name='total_credit_points',
            field=models.FloatField(),
        ),
    ]
